### ISSUE TITLE
ActivityNet dataset Problem

### ISSUE THREAD

**Issue by Lonicer** [Huntersxsx/MGPN#1]

**Comment by Lonicer** [comment]
Where did the sub_activitynet_v1-3.c3d.hdf5 file of the ActivityNet dataset come from?

**Comment by Huntersxsx** [comment]
> Where did the sub_activitynet_v1-3.c3d.hdf5 file of the ActivityNet dataset come from?


We use the features offered by [2D-TAN](https://rochester.app.box.com/s/8znalh6y5e82oml2lr7to8s6ntab6mav/folder/137471953557), you can download and unzip them.

**Comment by Lonicer** [comment]
> > Where did the sub_activitynet_v1-3.c3d.hdf5 file of the ActivityNet dataset come from?
> 
> We use the features offered by [2D-TAN](https://rochester.app.box.com/s/8znalh6y5e82oml2lr7to8s6ntab6mav/folder/137471953557), you can download and unzip them.
After I downloaded and decompressed, it was an npy file, and there was no hdf5 file, what should I do? Thank you
![image](https://user-images.githubusercontent.com/70836946/206129388-5c2998ce-6fcb-4d1d-a487-d912e06c2bb2.png)

**Comment by Huntersxsx** [comment]
> > > Where did the sub_activitynet_v1-3.c3d.hdf5 file of the ActivityNet dataset come from?
> > 
> > 
> > We use the features offered by [2D-TAN](https://rochester.app.box.com/s/8znalh6y5e82oml2lr7to8s6ntab6mav/folder/137471953557), you can download and unzip them.
> > After I downloaded and decompressed, it was an npy file, and there was no hdf5 file, what should I do? Thank you
> > ![image](https://user-images.githubusercontent.com/70836946/206129388-5c2998ce-6fcb-4d1d-a487-d912e06c2bb2.png)

Actually,  npy files can be merged into a hdf5 file in some way, you can refer to [py file](https://github.com/microsoft/VideoX/blob/master/2D-TAN/data/TACoS/merge_npys_to_hdf5.py). However, I remember we directly obtained the sub_activitynet_v1-3.c3d.hdf5 file after unzipping. Perhaps you can try this [download.sh](https://github.com/microsoft/VideoX/blob/master/2D-TAN/data/ActivityNet/download.sh)? The extracted C3D features are offered by [the official ActivityNet website](http://activity-net.org/challenges/2016/download.html)  in fact.

**Comment by Huntersxsx** [comment]
> > > Where did the sub_activitynet_v1-3.c3d.hdf5 file of the ActivityNet dataset come from?
> > 
> > 
> > We use the features offered by [2D-TAN](https://rochester.app.box.com/s/8znalh6y5e82oml2lr7to8s6ntab6mav/folder/137471953557), you can download and unzip them.
> > After I downloaded and decompressed, it was an npy file, and there was no hdf5 file, what should I do? Thank you
> > ![image](https://user-images.githubusercontent.com/70836946/206129388-5c2998ce-6fcb-4d1d-a487-d912e06c2bb2.png)

Hello, I'd like to know if the above [download.sh](https://github.com/microsoft/VideoX/blob/master/2D-TAN/data/ActivityNet/download.sh) is valid and have you successfully obtained the sub_activitynet_v1-3.c3d.hdf5 file ?

**Comment by Lonicer** [comment]
yes,I do.thank you!



发自我的iPad


------------------ Original ------------------
From: Sun Xin ***@***.***&gt;
Date: Fri,Dec 9,2022 3:58 PM
To: Huntersxsx/MGPN ***@***.***&gt;
Cc: 左云起 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Huntersxsx/MGPN] ActivityNet dataset Problem (Issue #1)





    
Where did the sub_activitynet_v1-3.c3d.hdf5 file of the ActivityNet dataset come from?
  
We use the features offered by 2D-TAN, you can download and unzip them.
 After I downloaded and decompressed, it was an npy file, and there was no hdf5 file, what should I do? Thank you
 
   
Hello, I'd like to know if the above download.sh is valid and have you successfully obtained the sub_activitynet_v1-3.c3d.hdf5 file ?
