### ISSUE TITLE
c3d and i3d features of charades-sta

### ISSUE THREAD

**Issue by enlikahlil** [Huntersxsx/MGPN#3]
Hi!Thanks for your meaningful work. 
I'm wondering where did the c3d feature and i3d features of the Charades-STA dataset come from,
Could you provide the code for extracting features or the extracted features?
Many thanks.

**Comment by akzeycgdn265** [comment]
Hello! Have you got the c3d feature and i3d features of the Charades-STA datasets? Can you share? Many thanks！
